# -*- coding: utf-8 -*-
"""l_pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M65Yt7yzyVqj0Q6y57KV0lPomY_S0N1C
"""

import pandas as pd

import numpy as np

from pandas import Series

obj1 = Series([1,2,3,4])

obj1

obj2=([2,5,3,2.4])

obj1*obj2

obj3=Series([1,2,3,4,5.5],index=["a","b","c","d","e"])

obj3["e"]

obj3[['a','e']]

np.exp(obj3)

index=['mashina2','mashina','mashina3']

dict1={"mashina":1222,"mashina2":3444}

f=Series(dict1,index=index)

f

'mashina' in f

'mashina3' in dict1

obj1.notnull()

obj1

obj1[12]=1211

obj1



obj2=([22,22,22,22,22,22,22])

obj1+obj2

obj1.index.name = "TT1"

obj1

obj1.name

obj3.values

obj3.dtype

obj3.shape

obj1[12]

import pandas as pd

data = {
    'ism':["Jamshid","Alijon","Asilbek","Sherzod"],
    "mablag'":[14000, 15500,12000,22000],
    "vaqt":["22.01.23","22.01.23","20.01.2022","unknown"]
}

index1=[1,2,3,4]

df=pd.DataFrame(data,index=[1,2,3,4],columns=['ism','vaqt',"mablag'",'joy','kim_tomonidan'])

df.head()

df.head(2)

df.shape

vaqt = df['vaqt']

vaqt

vaqt

type(vaqt)

df.joy="unknown yet"

df

df.joy[1]="qamashi"

df

df.joy[1:]='qarshi'

df

appn = pd.Series(["shaxs","shaxs","virt","qarz"], index= [2,3,1,4])

df.kim_tomonidan = appn

df

df["+"] = df.kim_tomonidan!='qarz'

df

df["to_attend"] = ["YES","YES","YES","YES"]

df

df.index.name="N%"

df

df.T

df.T

df.T.head

